### ISSUE TITLE
Strange ordering of fields

### ISSUE THREAD

**Issue by JoshBoluga** [vigneshuvi/SwiftCSVExport#1]
Am I doing something wrong here, because this code:

    let path = CSVExport.export.exportCSV(filename,
                                      fields: ["a", "b", "c"],
                                      values: [["a": 1, "b": 2, "c": 3],
                                               ["a": 4, "b": 5, "c": 6],
                                               ["a": 7, "b": 8, "c": 9]])

...produces this result:

    a,b,c
    2,1,3
    5,4,6
    8,7,9

**Comment by vignesh-bella** [comment]
@JoshBoluga  You were passing wrong argument type.

Framework only supports array of JSON string and NSDictionary. Like below.
```

        let string = "[{\"a\":1,\"b\":2,\"c\":3},{\"a\":4,\"b\":5,\"c\":6}]";
        let filePath:String = exportCSV("userlist", fields:["a","b","c"], values:string);
        print(filePath)
        
        
        let fileDetails = readCSV(filePath);
        if fileDetails.allKeys.count > 0 {
            print(fileDetails)
        }
        
        // First Row Object
        let row1:NSMutableDictionary = NSMutableDictionary()
        row1.setValue(1, forKey: "a" );
        row1.setValue(2, forKey: "b" );
        row1.setValue(3, forKey: "c" );

        
        // Secound Row Object
        let row2:NSMutableDictionary = NSMutableDictionary()
        row2.setValue(4, forKey: "a" );
        row2.setValue(5, forKey: "b" );
        row2.setValue(6, forKey: "c" );
        
        // 3rd Row Object
        let row3:NSMutableDictionary = NSMutableDictionary()
        row3.setValue(7, forKey: "a" );
        row3.setValue(8, forKey: "b" );
        row3.setValue(9, forKey: "c" );

        
        // Add dictionary into rows of CSV Array
        let data:NSMutableArray  = NSMutableArray()
        data.add(row1);
        data.add(row2);
        data.add(row3);


        
        let path:String = SwiftCSVExport.exportCSV("numberList",fields: ["a", "b","c"],values: data);
        print(path)
        
        let numberDetails = readCSV(path);
        if numberDetails.allKeys.count > 0 {
            print(numberDetails)
        }
```

**Comment by vignesh-bella** [comment]
Sorry, You can use as like below as of now. I will do fix accordingly.
```
 let numberArray = [["a": 1, "b": 2, "c": 3],
        ["a": 4, "b": 5, "c": 6],
        ["a": 7, "b": 8, "c": 9]]
        
        // Add dictionary into rows of CSV Array
        let data:NSMutableArray  = NSMutableArray()
      
        let fields =  ["a", "b","c"];
        for dict in numberArray {
            let row:NSMutableDictionary = NSMutableDictionary()
            for i in 0 ..< fields.count {
                row.setValue(dict[fields[i]], forKey: fields[i] );
            }
            data.add(row)
        }
        
        let path:String = SwiftCSVExport.exportCSV("numberList",fields: fields,values: data);
        print(path)
        
        let numberDetails = readCSV(path);
        if numberDetails.allKeys.count > 0 {
            print(numberDetails)
        }
```

**Comment by vigneshuvi** [comment]
Framework only supports array of JSON string and NSDictionary. Like below.


        let string = "[{\"a\":1,\"b\":2,\"c\":3},{\"a\":4,\"b\":5,\"c\":6}]";
        let filePath:String = exportCSV("userlist", fields:["a","b","c"], values:string);
        print(filePath)
        
        
        let fileDetails = readCSV(filePath);
        if fileDetails.allKeys.count > 0 {
            print(fileDetails)
        }
        
        // First Row Object
        let row1:NSMutableDictionary = NSMutableDictionary()
        row1.setValue(1, forKey: "a" );
        row1.setValue(2, forKey: "b" );
        row1.setValue(3, forKey: "c" );

        
        // Secound Row Object
        let row2:NSMutableDictionary = NSMutableDictionary()
        row2.setValue(4, forKey: "a" );
        row2.setValue(5, forKey: "b" );
        row2.setValue(6, forKey: "c" );
        
        // 3rd Row Object
        let row3:NSMutableDictionary = NSMutableDictionary()
        row3.setValue(7, forKey: "a" );
        row3.setValue(8, forKey: "b" );
        row3.setValue(9, forKey: "c" );

        
        // Add dictionary into rows of CSV Array
        let data:NSMutableArray  = NSMutableArray()
        data.add(row1);
        data.add(row2);
        data.add(row3);


        
        let path:String = SwiftCSVExport.exportCSV("numberList",fields: ["a", "b","c"],values: data);
        print(path)
        
        let numberDetails = readCSV(path);
        if numberDetails.allKeys.count > 0 {
            print(numberDetails)
        }

Sorry, You can use as like below as of now. I will do fix accordingly.

        let numberArray = [["a": 1, "b": 2, "c": 3],
            ["a": 4, "b": 5, "c": 6],
            ["a": 7, "b": 8, "c": 9]]
        
        // Add dictionary into rows of CSV Array
        let data:NSMutableArray  = NSMutableArray()
      
        let fields =  ["a", "b","c"];
        for dict in numberArray {
            let row:NSMutableDictionary = NSMutableDictionary()
            for i in 0 ..< fields.count {
                row.setValue(dict[fields[i]], forKey: fields[i] );
            }
            data.add(row)
        }
        
        let path:String = SwiftCSVExport.exportCSV("numberList",fields: fields,values: data);
        print(path)
        
        let numberDetails = readCSV(path);
        if numberDetails.allKeys.count > 0 {
            print(numberDetails)
        }

**Comment by JoshBoluga** [comment]
Cool. Thanks.

**Comment by vigneshuvi** [comment]
Try with SwiftCSVExport (1.0.2)

**Comment by DogandElk** [comment]
First | Last | Company | Address1 | Address2 | City | State | Postalcode | Country | Sender | Frontimage | Backtext | Accentimage | Backimage |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Loma Linda | Back Image | Back Text | 2nd Floor | Mary Ann | Missouri | 64804 | Fuller | 4 States Printing | Accent Image | Record ID | Rusty | 12345678 | Front Image | United States | 1234 Appaloosa Way


I'm getting strange formatting

**Comment by vigneshuvi** [comment]
New version 1.0.4 released. 

Release Note: https://github.com/vigneshuvi/SwiftCSVExport/releases/tag/1.0.4

**Comment by kedolg** [comment]
Good Morning,

I just updated the SwiftCVSExport pod and the strange ordering issue is fixed, however, it is not populating one of the fields, the BackText field is empty. See below:

DMID
RECORDID
First
Last
Company
Address1
Address2
City
State
Postalcode
Country
Sender
Frontimage
Backtext
Accentimage
Backimage
123456789
PCA12345D
Leah
Schmidt
Lab Cab Inc
5442 Appaloosa Way
First Floor
Loma Linda
Missouri
64804
USA
Annie
Picture of Roo

NO Accent Image
NO Back Image

I checked all the code, but I must be missing something.  I will continue to troubleshoot and let you know if I can figure it out. If you have any suggestions, I would be very appreciative.

I would also like to place a positive recommendation on the Cocoapods site for you as you have been fantastic in helping to get the issue I raised fixed.

Thanks again !

Tom

**Comment by vigneshuvi** [comment]
@kedolg 

I will look into your code again and let you know.

Can you please provide your "Backtext" string?

**Comment by vigneshuvi** [comment]
Hi @kedolg ,
You have used wrong field key to generate CSV file.

```
user1.setObject("Back Text", forKey: "BackText" as NSCopying);          //optional

  let filePath:String = SwiftCSVExport.exportCSV("userlist1",fields: ["DMID", "RecordID", "First", "Last", "Company","Address1", "Address2", "City", "State", "Postalcode", "Country", "Sender","Frontimage", "Backtext", "Accentimage","Backimage"],values: data);

```

"BackText"  or "Backtext" ?


Note: Please maintain consistency between keys which you used in Dictionary and Field Array.

**Comment by kedolg** [comment]
Thanks for responding. 

I sent you an earlier email in which I let you know that I discovered I had a typo , ugh.
Once I fixed the typo, the field populated well.

One thing.... You cannot use any punctuation in the string otherwise, things get jumbled.

 If my users enter punctuation like commas and periods in their messages, they will get jumbled output in the csv file.

Is there a way around that ? 

Thanks for getting back to me. 

I really appreciate your assistance.

**Comment by vigneshuvi** [comment]
@kedolg ,

Will work on punctuation staff and will release new build. 

As of now, I have replaced "\n", "\t" and "\r" with empty string.

**Comment by kedolg** [comment]
Sounds Great !

Thanks again !

Curious where you are located ?

**Comment by vigneshuvi** [comment]
@kedolg , 

I have handled the punctuation too! I will release version 1.0.5  by tomorrow.

Enjoy with my framework!

I'm from India, Tamil-nadu and my [profile](http://vigneshuvi.github.io/).

**Comment by kedolg** [comment]
You are Awesome !

Thanks again.

I sent you another email asking about how I would send the cvs file to a cloud storage site like AWS. Does your framework have a functionality for that  ?

Thanks !

Tom

**Comment by vigneshuvi** [comment]
Hi @kedolg & @DogandElk

🚀 SwiftCSVExport (1.0.5) successfully published
📅 November 7th, 21:07
🌎 https://cocoapods.org/pods/SwiftCSVExport

[Release note](https://github.com/vigneshuvi/SwiftCSVExport/releases/tag/1.0.5)

iCloud is big staff. We have to configure in developers account and so on!

[Enable iCloud from here!
](
https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitQuickStart/EnablingiCloudandConfiguringCloudKit/EnablingiCloudandConfiguringCloudKit.html)

**Comment by DogandElk** [comment]
Sounds good.

I just tried to update the pod and it still only finds SwiftCSVExport 1.04.

Analyzing dependencies
Downloading dependencies

Using SwiftCSVExport (1.0.4)

Using SwiftLoggly (1.0.5)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.


Does it take time for that to propagate through the Cocoapods server ?

Thanks !

**Comment by vigneshuvi** [comment]
@DogandElk ,
Have you changed Podfile as like below?

`pod 'SwiftCSVExport', :git => 'https://github.com/vigneshuvi/SwiftCSVExport.git', :tag => '1.0.4'`
into
`pod 'SwiftCSVExport'`

![screen shot 2017-11-08 at 11 33 43 am](https://user-images.githubusercontent.com/4980335/32533863-cb6f853c-c478-11e7-975b-2598533ef90c.png)

**Comment by DogandElk** [comment]
Hi !

I reinstalled again and the 1.05 version loaded and the formatting issue is working perfectly.
You are Awesome !
Thank you very much for helping out.
I really appreciate your attention and assistance.
I am just learning github and would like to know exactly which files I would need to add to an existing project to implement the functionality of your app to create the csv files in my project.
Thanks again !
Tom
