### ISSUE TITLE
Row with same values as fields won't be imported

### ISSUE THREAD

**Issue by elijah-rappaport** [vigneshuvi/SwiftCSVExport#11]
If a row happens to have the same values as the fields, that row won't be imported.

e.g.
col1,col2,col3
a,b,c
col1,col2,col3

will ignore the last row

**Comment by vigneshuvi** [comment]
Why framework need to ignore the last row?

**Comment by elijah-rappaport** [comment]
You shouldn't. But you are.

**Comment by vigneshuvi** [comment]
Can you please explain, why we need to ignore the last row?

**Comment by elijah-rappaport** [comment]
You should not be ignoring the last row. But your framework currently is ignoring it. Try the example and you will see.  You will end up with a csv with just one row, which is incorrect.

**Comment by vigneshuvi** [comment]
`
    // First User Object
    NSMutableDictionary *user1 = [NSMutableDictionary new];
    [user1 setValue:@"vignesh" forKey:@"name" ];
    [user1 setValue:@"vigneshuvi@gmail.com" forKey: @"email"];
    
    
    // Secound User Object
    NSMutableDictionary *user2 = [NSMutableDictionary new];
    [user2 setValue:@"vinoth" forKey:@"name" ];
    [user2 setValue:@"vigneshuvi@gmail.com" forKey: @"email"];
    // Secound User Object
    NSMutableDictionary *user3 = [NSMutableDictionary new];
    [user3 setValue:@"name" forKey:@"name" ];
    [user3 setValue:@"email" forKey: @"email"];
    
    
    // CSV fields Array
    NSMutableArray *fields = [NSMutableArray new];
    [fields addObject:@"name"];
    [fields addObject:@"email"];
    
    // CSV rows Array
    NSMutableArray *data = [NSMutableArray new];
    [data addObject:user1];
    [data addObject:user2];
    [data addObject:user3];
    
    

    
    // Create a object for write CSV
    CSV *writeCSVObj = [[CSV alloc] init];
    writeCSVObj.rows = data;
    writeCSVObj.fields = fields;
    //writeCSVObj.delimiter = DividerTypeComma;
    writeCSVObj.name = @"userlist";
    
    // Write File using CSV class object
    CSVResult *outPut = [CSVExport exportCSV:writeCSVObj];
    if (outPut.result == ResultValid) {
       NSLog(@"Export Validate.");
    } else {
        NSLog(@"Export Invalidate.");
    }
    // REad cSv file
    CSV *readCSV = [CSVExport readCSVObjectFromDefaultPath:@"userlist.csv"];
    if (readCSV != nil) {
        NSLog(@"Export Validate.");
    } else {
        NSLog(@"Export Invalidate.");
    }
`

I tried this input its working fine for both read and write.

**Comment by elijah-rappaport** [comment]
What you just wrote has nothing to do with the issue.
Your software is supposed to take a csv file as input and convert it to an object.
Please try your software with the attached csv file.
[test.txt](https://github.com/vigneshuvi/SwiftCSVExport/files/1771824/test.txt)

**Comment by vigneshuvi** [comment]
Thanks for let me know. Can you please try with latest version 2.0.1??
