### ISSUE TITLE
Support chinese language

### ISSUE THREAD

**Issue by KohFujimura** [vigneshuvi/SwiftCSVExport#16]
Please support Chinese language, all chinese text is not shown :(

**Comment by vigneshuvi** [comment]
Please give your sample inputs, I will give support asap.

**Comment by vigneshuvi** [comment]
@KohFujimura , Can you please provide sample inputs. Otherwise, I am going to close this ticket.

**Comment by AlaghbariKamel** [comment]
Hi I test your code on my emulator with Arabic language text and give me like  ŸÉÿßŸÖŸÑ  , but on my real device working fine

**Comment by vigneshuvi** [comment]
@2020KamelAlaghbari , I have tried with Arabic language in simulator. It is working fine. Can you please provide valid example?

**Comment by vigneshuvi** [comment]
https://github.com/vigneshuvi/SwiftCSVExport/commit/0af1704d63036639ce9c7cdce446090fa9172df6

Chinese and above example texts are add in the example.
