### ISSUE TITLE
How can I install and import SwiftCSVExport to macOS project?

### ISSUE THREAD

**Issue by instantback** [vigneshuvi/SwiftCSVExport#18]
@vigneshuvi how can I install and import SwiftCSVExport framework via CocoaPods to macOS project?

`import SwiftCSVExportOSX` isn't working with `platform :osx` in Podfile (with `platform :ios` as well).

Thank you!

**Comment by vigneshuvi** [comment]
@instantback , Can you please let me know what is your App project swift version?

**Comment by instantback** [comment]
@vigneshuvi Swift 5

**Comment by vigneshuvi** [comment]
@instantback , I have created the same project.
https://github.com/vigneshuvi/SwiftCSVExport/tree/master/Examples/MacOS/SampleMacSwift

**Comment by vigneshuvi** [comment]
@instantback , I have created the same project.
https://github.com/vigneshuvi/SwiftCSVExport/tree/master/Examples/MacOS/SampleMacSwift
