### ISSUE TITLE
Cocoa pod not working.

### ISSUE THREAD

**Issue by tejas-ardeshna** [vigneshuvi/SwiftCSVExport#2]
Might be there is an issue with the current pod. it is not working on the project. See below image.
the pod is just adding .h file source file is missing. 
![screen shot 2017-07-12 at 12 39 27 pm](https://user-images.githubusercontent.com/12891361/28105888-2c211bb6-66ff-11e7-8cf7-74ebda7c00ab.png)

**Comment by vigneshuvi** [comment]
Hi @tejas-ardeshna , Are you using my example project? What is your cocoa-pod version?

**Comment by vigneshuvi** [comment]
_Please find it and check your pod version and framework version in your project._ 

$ pod install
... Analyzing dependencies
... Downloading dependencies
... Installing SwiftCSVExport (1.0.2)
... Installing SwiftLoggly (1.0.4)
... Generating Pods project
... Integrating client project

![screen shot 2017-07-12 at 1 10 29 pm](https://user-images.githubusercontent.com/4980335/28107006-a630ffbc-6703-11e7-9e99-8e37adc56f9b.png)

**Comment by tejas-ardeshna** [comment]
Thanks man, worked with 'pod repo update'.

one more question. can i use this lib in objective c project.

**Comment by vigneshuvi** [comment]
Yeah, you can use this framework in the Objective-C project. I have updated the readme file. Please let me know if want any help.
