### ISSUE TITLE
SwiftPM in Xcode 12: Failed to resolve dependencies.

### ISSUE THREAD

**Issue by Jeehut** [vigneshuvi/SwiftCSVExport#23]
When adding this library to an iOS project via Xcodes SwiftPM functionality, I get this error:

```bash
because SwiftCSVExport >=1.0.0 contains incompatible tools version and root depends on SwiftCSVExport 2.3.0..<3.0.0, version solving failed.
```

**Comment by willm132** [comment]
I am getting this error also. Can someone update with a resolution?

**Comment by willm132** [comment]
@Jeehut your pull request build failed

**Comment by Jeehut** [comment]
@willm132 Of course it failed, I didn't add a test target. I could have a look tomorrow, working time is over for me for today (in Germany). Didn't know you had a CI in place that was running SwiftPM tests ...

**Comment by willm132** [comment]
Awesome. Let me know if you get it working, I’m interested in using this in my app.

**Comment by willm132** [comment]
I emailed the owner via his website to see if he could update it but he has no responded
