### ISSUE TITLE
Cannot find 'exportCSV' in scope

### ISSUE THREAD

**Issue by willm132** [vigneshuvi/SwiftCSVExport#25]
I was able to add the Package Manager but I am getting this error:

`let result = exportCSV(writeCSVObj);` --> `Cannot find 'exportCSV' in scope`

I have already imported SwiftCSVExport

**Comment by vigneshuvi** [comment]
@willm132 , i will take look now and reverted back before end of today.

**Comment by willm132** [comment]
@vigneshuvi Any updates on this issue? Very excited to get this running inside all of my applications

**Comment by willm132** [comment]
> @willm132 , i will take look now and reverted back before end of today.

@vigneshuvi Any updates on this issue? Very excited to get this running inside all of my applications

**Comment by willm132** [comment]
You can close this issue. I was able to get it resolved. You need to change the instructions on your main page from this:

`let result = exportCSV(writeCSVObj);`

to this:

`let result = CSVExport.export(writeCSVObj);`
