### ISSUE TITLE
Directory for CSV file does not get created in IOS

### ISSUE THREAD

**Issue by kedolg** [vigneshuvi/SwiftCSVExport#3]
I am developing an iPhone app using Xcode 9 and Swift 4. I have followed your installation instructions meticulously and I have attempted to create a CSV file. When I run the app the cdv file never gets populated into the directory in the app documents folder . I reviewed the CSVExport.swift file and I see the following code 👍  

///get the default CSV directory

    class func defaultDirectory() -> String {
        var path = "/SampleSwift"
        let fileManager = FileManager.default
        #if os(iOS)
            let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
            path = "\(path[0])/Exports"
        #elseif os(OSX)
            let urls = fileManager.urls(for: .libraryDirectory, in: .userDomainMask)
            if let url = urls.last?.path {
                paths = "\(url)/Exports"
            }
        #endif
        if !fileManager.fileExists(atPath: path) && path != ""  {
            do {
                try fileManager.createDirectory(atPath: path, withIntermediateDirectories: false, attributes: nil)
            } catch _ {
            }
        }
        return path
    }

I have an iPhone 7 plus connected as a test device. I never receive any runtime errors. The console displays  the following path for the userlist1.csv file 👍 

/var/mobile/Containers/Data/Application/13DB9A0A-774C-45B0-A753-62FF8C56CF11/Documents/Exports/userlist1.csv

How do I get access to that file ? It never gets populated into the apps documents folder and the Exports folder never gets created. 

I would appreciate any assistance you can offer .
thanks !
Tom

**Comment by DogandElk** [comment]
It's been ten days since I submitted a question with no response. Are you no longer supporting your work ? If not, I will inform cocoa pods that you are not.

**Comment by DogandElk** [comment]
We discovered that when using a connected device, the file gets created on the device itself, however, it is not visible. To see the file, one must use an application like iMazing. They have free version as well as paid versions with more functionality.

**Comment by vigneshuvi** [comment]
Hi @kedolg @DogandElk ,

Bundle display name - "APPLICATION NAME"
Application requires iPhone environment - YES
Supports opening documents in place - YES
Application supports iTunes file sharing - YES


This is not SwiftCSVExport framework issue. Add above key's in your project. Then, you can see those files in the iOS Files app.

**Comment by kedolg** [comment]
Good Morning,

Thank you for evaluating this issue. How would I add these keys to the project ? I have not done this before. Your guidance would be very much appreciated .

Thanks again !

**Comment by vigneshuvi** [comment]
@kedolg,

You have to add those keys in app .plist file. Please find the reference or review my SampleSwift project.

Reference: https://github.com/vigneshuvi/SwiftCSVExport/blob/master/Examples/SampleSwift/SampleSwift/Info.plist

**Comment by kedolg** [comment]
Hi Again,

The missing field was due to a typo, ugh.

Thanks so much for helping get this issue resolved.

I added the other keys to the info.plist file as suggested.

Thanks again !


Now the last thing I want to do is to export this file to a cloud based storage device as soon as the file is created. Is there a specific location where I can add that url to make this happen automatically ?

Thanks !

Tom

**Comment by vigneshuvi** [comment]
Hi @kedolg & @DogandElk 

 🚀  SwiftCSVExport (1.0.5) successfully published
 📅  November 7th, 21:07
 🌎  https://cocoapods.org/pods/SwiftCSVExport

_[Release note](https://github.com/vigneshuvi/SwiftCSVExport/releases/tag/1.0.5)_

iCloud is big staff. We have to configure in developers account and so on!
