### ISSUE TITLE
String quotes

### ISSUE THREAD

**Issue by lazar89nis** [vigneshuvi/SwiftCSVExport#9]
Hi,
First of all great library. I am using it for some time for my application. In last version strings didn't have quotes around them, and in this new version, there are. Can you make them optional with some parameter for settings?

I changed: let fString = "\(string)" to get rid of quotes.

Thanks

**Comment by vigneshuvi** [comment]
@lazar89nis , I hope it's added in the new version. Thanks for your suggestion.

**Comment by ImpacGroup** [comment]
In the version 2.3.0 are still quotes for the first string in a row. This ticket should not be closed.

**Comment by chambefc** [comment]
Still not resolved

**Comment by willm132** [comment]
@vigneshuvi This is happening for me, the first row of string has a ' around it. Anyway to disable this?
